// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'60a2aa056297be09fd6089f7f4ee565f9d84979c159d57ce279ee94c3d779e4f'>;
export type ExecutionHash =
  ExecutionHashBase<'d87876b994ba8b2e48ba0f2cbd228a300e06ab8a720b7ea5d8ac70bdf515317a'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Booking: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly reference: CodecTypes['pg/text@1']['output'];
      readonly customerId: CodecTypes['pg/text@1']['output'];
      readonly locationId: CodecTypes['pg/text@1']['output'];
      readonly protocolId: CodecTypes['pg/text@1']['output'];
      readonly membershipId: CodecTypes['pg/text@1']['output'] | null;
      readonly date: CodecTypes['pg/text@1']['output'];
      readonly time: CodecTypes['pg/text@1']['output'];
      readonly customerName: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly phone: CodecTypes['pg/text@1']['output'];
      readonly membershipName: CodecTypes['pg/text@1']['output'] | null;
      readonly status: 'PENDING' | 'CONFIRMED' | 'COMPLETED' | 'CANCELLED' | 'REJECTED';
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Customer: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly phone: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Location: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly region: CodecTypes['pg/text@1']['output'];
      readonly country: CodecTypes['pg/text@1']['output'];
      readonly status: 'ACTIVE' | 'EXPANSION';
      readonly phase: CodecTypes['pg/int4@1']['output'];
      readonly type: CodecTypes['pg/text@1']['output'];
      readonly address: CodecTypes['pg/text@1']['output'] | null;
      readonly landmark: CodecTypes['pg/text@1']['output'] | null;
      readonly phone: CodecTypes['pg/text@1']['output'];
      readonly bookingEnabled: CodecTypes['pg/bool@1']['output'];
      readonly clinicEnabled: CodecTypes['pg/bool@1']['output'];
      readonly atHomeEnabled: CodecTypes['pg/bool@1']['output'];
      readonly nadxEnabled: CodecTypes['pg/bool@1']['output'];
    };
    readonly Membership: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly type: 'PACKAGE' | 'UNLIMITED' | 'CIRCLE';
      readonly monthlyPrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly packagePrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly gst: CodecTypes['pg/numeric@1']['output'] | null;
      readonly totalPrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly active: CodecTypes['pg/bool@1']['output'];
    };
    readonly Protocol: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly number: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly family: CodecTypes['pg/text@1']['output'];
      readonly category: CodecTypes['pg/text@1']['output'];
      readonly shortDescription: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly duration: CodecTypes['pg/text@1']['output'];
      readonly price: CodecTypes['pg/numeric@1']['output'] | null;
      readonly image: CodecTypes['pg/text@1']['output'];
      readonly evidenceTier: CodecTypes['pg/text@1']['output'];
      readonly active: CodecTypes['pg/bool@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Booking: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly reference: CodecTypes['pg/text@1']['input'];
      readonly customerId: CodecTypes['pg/text@1']['input'];
      readonly locationId: CodecTypes['pg/text@1']['input'];
      readonly protocolId: CodecTypes['pg/text@1']['input'];
      readonly membershipId: CodecTypes['pg/text@1']['input'] | null;
      readonly date: CodecTypes['pg/text@1']['input'];
      readonly time: CodecTypes['pg/text@1']['input'];
      readonly customerName: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly phone: CodecTypes['pg/text@1']['input'];
      readonly membershipName: CodecTypes['pg/text@1']['input'] | null;
      readonly status: 'PENDING' | 'CONFIRMED' | 'COMPLETED' | 'CANCELLED' | 'REJECTED';
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Customer: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly phone: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Location: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly region: CodecTypes['pg/text@1']['input'];
      readonly country: CodecTypes['pg/text@1']['input'];
      readonly status: 'ACTIVE' | 'EXPANSION';
      readonly phase: CodecTypes['pg/int4@1']['input'];
      readonly type: CodecTypes['pg/text@1']['input'];
      readonly address: CodecTypes['pg/text@1']['input'] | null;
      readonly landmark: CodecTypes['pg/text@1']['input'] | null;
      readonly phone: CodecTypes['pg/text@1']['input'];
      readonly bookingEnabled: CodecTypes['pg/bool@1']['input'];
      readonly clinicEnabled: CodecTypes['pg/bool@1']['input'];
      readonly atHomeEnabled: CodecTypes['pg/bool@1']['input'];
      readonly nadxEnabled: CodecTypes['pg/bool@1']['input'];
    };
    readonly Membership: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly type: 'PACKAGE' | 'UNLIMITED' | 'CIRCLE';
      readonly monthlyPrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly packagePrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly gst: CodecTypes['pg/numeric@1']['input'] | null;
      readonly totalPrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly active: CodecTypes['pg/bool@1']['input'];
    };
    readonly Protocol: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly number: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly family: CodecTypes['pg/text@1']['input'];
      readonly category: CodecTypes['pg/text@1']['input'];
      readonly shortDescription: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly duration: CodecTypes['pg/text@1']['input'];
      readonly price: CodecTypes['pg/numeric@1']['input'] | null;
      readonly image: CodecTypes['pg/text@1']['input'];
      readonly evidenceTier: CodecTypes['pg/text@1']['input'];
      readonly active: CodecTypes['pg/bool@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly booking: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly customerId: CodecTypes['pg/text@1']['output'];
      readonly customerName: CodecTypes['pg/text@1']['output'];
      readonly date: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly locationId: CodecTypes['pg/text@1']['output'];
      readonly membershipId: CodecTypes['pg/text@1']['output'] | null;
      readonly membershipName: CodecTypes['pg/text@1']['output'] | null;
      readonly phone: CodecTypes['pg/text@1']['output'];
      readonly protocolId: CodecTypes['pg/text@1']['output'];
      readonly reference: CodecTypes['pg/text@1']['output'];
      readonly status: 'PENDING' | 'CONFIRMED' | 'COMPLETED' | 'CANCELLED' | 'REJECTED';
      readonly time: CodecTypes['pg/text@1']['output'];
    };
    readonly customer: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly phone: CodecTypes['pg/text@1']['output'];
    };
    readonly location: {
      readonly address: CodecTypes['pg/text@1']['output'] | null;
      readonly atHomeEnabled: CodecTypes['pg/bool@1']['output'];
      readonly bookingEnabled: CodecTypes['pg/bool@1']['output'];
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly clinicEnabled: CodecTypes['pg/bool@1']['output'];
      readonly country: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly landmark: CodecTypes['pg/text@1']['output'] | null;
      readonly nadxEnabled: CodecTypes['pg/bool@1']['output'];
      readonly phase: CodecTypes['pg/int4@1']['output'];
      readonly phone: CodecTypes['pg/text@1']['output'];
      readonly region: CodecTypes['pg/text@1']['output'];
      readonly status: 'ACTIVE' | 'EXPANSION';
      readonly type: CodecTypes['pg/text@1']['output'];
    };
    readonly membership: {
      readonly active: CodecTypes['pg/bool@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly gst: CodecTypes['pg/numeric@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly monthlyPrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly packagePrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly totalPrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly type: 'PACKAGE' | 'UNLIMITED' | 'CIRCLE';
    };
    readonly protocol: {
      readonly active: CodecTypes['pg/bool@1']['output'];
      readonly category: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly duration: CodecTypes['pg/text@1']['output'];
      readonly evidenceTier: CodecTypes['pg/text@1']['output'];
      readonly family: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly image: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly number: CodecTypes['pg/int4@1']['output'];
      readonly price: CodecTypes['pg/numeric@1']['output'] | null;
      readonly shortDescription: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly booking: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly customerId: CodecTypes['pg/text@1']['input'];
      readonly customerName: CodecTypes['pg/text@1']['input'];
      readonly date: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly locationId: CodecTypes['pg/text@1']['input'];
      readonly membershipId: CodecTypes['pg/text@1']['input'] | null;
      readonly membershipName: CodecTypes['pg/text@1']['input'] | null;
      readonly phone: CodecTypes['pg/text@1']['input'];
      readonly protocolId: CodecTypes['pg/text@1']['input'];
      readonly reference: CodecTypes['pg/text@1']['input'];
      readonly status: 'PENDING' | 'CONFIRMED' | 'COMPLETED' | 'CANCELLED' | 'REJECTED';
      readonly time: CodecTypes['pg/text@1']['input'];
    };
    readonly customer: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly phone: CodecTypes['pg/text@1']['input'];
    };
    readonly location: {
      readonly address: CodecTypes['pg/text@1']['input'] | null;
      readonly atHomeEnabled: CodecTypes['pg/bool@1']['input'];
      readonly bookingEnabled: CodecTypes['pg/bool@1']['input'];
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly clinicEnabled: CodecTypes['pg/bool@1']['input'];
      readonly country: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly landmark: CodecTypes['pg/text@1']['input'] | null;
      readonly nadxEnabled: CodecTypes['pg/bool@1']['input'];
      readonly phase: CodecTypes['pg/int4@1']['input'];
      readonly phone: CodecTypes['pg/text@1']['input'];
      readonly region: CodecTypes['pg/text@1']['input'];
      readonly status: 'ACTIVE' | 'EXPANSION';
      readonly type: CodecTypes['pg/text@1']['input'];
    };
    readonly membership: {
      readonly active: CodecTypes['pg/bool@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly gst: CodecTypes['pg/numeric@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly monthlyPrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly packagePrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly totalPrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly type: 'PACKAGE' | 'UNLIMITED' | 'CIRCLE';
    };
    readonly protocol: {
      readonly active: CodecTypes['pg/bool@1']['input'];
      readonly category: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly duration: CodecTypes['pg/text@1']['input'];
      readonly evidenceTier: CodecTypes['pg/text@1']['input'];
      readonly family: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly image: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly number: CodecTypes['pg/int4@1']['input'];
      readonly price: CodecTypes['pg/numeric@1']['input'] | null;
      readonly shortDescription: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Customer = {
    id: CodecTypes['pg/text@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    phone: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    bookings: public_Booking[];
    readonly [RelationKeys]?: 'bookings';
  };
  export type public_Location = {
    id: CodecTypes['pg/text@1']['output'];
    city: CodecTypes['pg/text@1']['output'];
    region: CodecTypes['pg/text@1']['output'];
    country: CodecTypes['pg/text@1']['output'];
    status: 'ACTIVE' | 'EXPANSION';
    phase: CodecTypes['pg/int4@1']['output'];
    type: CodecTypes['pg/text@1']['output'];
    address: CodecTypes['pg/text@1']['output'] | null;
    landmark: CodecTypes['pg/text@1']['output'] | null;
    phone: CodecTypes['pg/text@1']['output'];
    bookingEnabled: CodecTypes['pg/bool@1']['output'];
    clinicEnabled: CodecTypes['pg/bool@1']['output'];
    atHomeEnabled: CodecTypes['pg/bool@1']['output'];
    nadxEnabled: CodecTypes['pg/bool@1']['output'];
    bookings: public_Booking[];
    readonly [RelationKeys]?: 'bookings';
  };
  export type public_Protocol = {
    id: CodecTypes['pg/text@1']['output'];
    slug: CodecTypes['pg/text@1']['output'];
    number: CodecTypes['pg/int4@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    family: CodecTypes['pg/text@1']['output'];
    category: CodecTypes['pg/text@1']['output'];
    shortDescription: CodecTypes['pg/text@1']['output'];
    description: CodecTypes['pg/text@1']['output'];
    duration: CodecTypes['pg/text@1']['output'];
    price: CodecTypes['pg/numeric@1']['output'] | null;
    image: CodecTypes['pg/text@1']['output'];
    evidenceTier: CodecTypes['pg/text@1']['output'];
    active: CodecTypes['pg/bool@1']['output'];
    bookings: public_Booking[];
    readonly [RelationKeys]?: 'bookings';
  };
  export type public_Membership = {
    id: CodecTypes['pg/text@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    type: 'PACKAGE' | 'UNLIMITED' | 'CIRCLE';
    monthlyPrice: CodecTypes['pg/numeric@1']['output'] | null;
    packagePrice: CodecTypes['pg/numeric@1']['output'] | null;
    gst: CodecTypes['pg/numeric@1']['output'] | null;
    totalPrice: CodecTypes['pg/numeric@1']['output'] | null;
    description: CodecTypes['pg/text@1']['output'] | null;
    active: CodecTypes['pg/bool@1']['output'];
    bookings: public_Booking[];
    readonly [RelationKeys]?: 'bookings';
  };
  export type public_Booking = {
    id: CodecTypes['pg/text@1']['output'];
    reference: CodecTypes['pg/text@1']['output'];
    customerId: CodecTypes['pg/text@1']['output'];
    locationId: CodecTypes['pg/text@1']['output'];
    protocolId: CodecTypes['pg/text@1']['output'];
    membershipId: CodecTypes['pg/text@1']['output'] | null;
    date: CodecTypes['pg/text@1']['output'];
    time: CodecTypes['pg/text@1']['output'];
    customerName: CodecTypes['pg/text@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    phone: CodecTypes['pg/text@1']['output'];
    membershipName: CodecTypes['pg/text@1']['output'] | null;
    status: 'PENDING' | 'CONFIRMED' | 'COMPLETED' | 'CANCELLED' | 'REJECTED';
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    customer: public_Customer;
    location: public_Location;
    membership: public_Membership | null;
    protocol: public_Protocol;
    readonly [RelationKeys]?: 'customer' | 'location' | 'membership' | 'protocol';
  };
}

export declare const models: {
  public: {
    Customer: Models.public_Customer;
    Location: Models.public_Location;
    Protocol: Models.public_Protocol;
    Membership: Models.public_Membership;
    Booking: Models.public_Booking;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly booking: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly reference: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly customerId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly locationId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly protocolId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly membershipId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly date: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly time: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly customerName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly phone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly membershipName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['reference'] }];
              indexes: readonly [
                {
                  readonly name: 'booking_customerId_idx_b2a8a46c';
                  readonly prefix: 'booking_customerId_idx';
                  readonly columns: readonly ['customerId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'booking_locationId_idx_7aae3038';
                  readonly prefix: 'booking_locationId_idx';
                  readonly columns: readonly ['locationId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'booking_protocolId_idx_628b4ed8';
                  readonly prefix: 'booking_protocolId_idx';
                  readonly columns: readonly ['protocolId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'booking_membershipId_idx_fdcfb7b5';
                  readonly prefix: 'booking_membershipId_idx';
                  readonly columns: readonly ['membershipId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'booking_status_idx_e98638ab';
                  readonly prefix: 'booking_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
                {
                  readonly name: 'booking_date_idx_b4ca319c';
                  readonly prefix: 'booking_date_idx';
                  readonly columns: readonly ['date'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'booking';
                    readonly columns: readonly ['customerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'customer';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'booking';
                    readonly columns: readonly ['locationId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'location';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'booking';
                    readonly columns: readonly ['protocolId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'protocol';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'booking';
                    readonly columns: readonly ['membershipId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'membership';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly customer: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly phone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly location: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly city: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly region: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly country: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly phase: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly address: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly landmark: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly phone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly bookingEnabled: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly clinicEnabled: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly atHomeEnabled: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly nadxEnabled: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly membership: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly monthlyPrice: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly packagePrice: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly gst: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly totalPrice: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly active: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly protocol: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly slug: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly number: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly family: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly category: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly shortDescription: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly duration: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly price: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly image: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly evidenceTier: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly active: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['slug'] },
                { readonly columns: readonly ['number'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly BookingStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'PENDING',
                'CONFIRMED',
                'COMPLETED',
                'CANCELLED',
                'REJECTED',
              ];
            };
            readonly LocationStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ACTIVE', 'EXPANSION'];
            };
            readonly MembershipType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PACKAGE', 'UNLIMITED', 'CIRCLE'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly customer: { readonly namespace: 'public' & NamespaceId; readonly model: 'Customer' };
    readonly location: { readonly namespace: 'public' & NamespaceId; readonly model: 'Location' };
    readonly protocol: { readonly namespace: 'public' & NamespaceId; readonly model: 'Protocol' };
    readonly membership: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Membership';
    };
    readonly booking: { readonly namespace: 'public' & NamespaceId; readonly model: 'Booking' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Booking: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly reference: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly customerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly locationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly protocolId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly membershipId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly date: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly time: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly customerName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly phone: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly membershipName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly customer: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Customer';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['customerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly location: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Location';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['locationId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly membership: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Membership';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['membershipId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly protocol: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Protocol';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['protocolId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'booking';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly reference: { readonly column: 'reference' };
                readonly customerId: { readonly column: 'customerId' };
                readonly locationId: { readonly column: 'locationId' };
                readonly protocolId: { readonly column: 'protocolId' };
                readonly membershipId: { readonly column: 'membershipId' };
                readonly date: { readonly column: 'date' };
                readonly time: { readonly column: 'time' };
                readonly customerName: { readonly column: 'customerName' };
                readonly email: { readonly column: 'email' };
                readonly phone: { readonly column: 'phone' };
                readonly membershipName: { readonly column: 'membershipName' };
                readonly status: { readonly column: 'status' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Customer: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly phone: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly bookings: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Booking';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['customerId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'customer';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly email: { readonly column: 'email' };
                readonly phone: { readonly column: 'phone' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Location: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly city: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly region: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly country: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly phase: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly address: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly landmark: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly phone: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly bookingEnabled: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly clinicEnabled: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly atHomeEnabled: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly nadxEnabled: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly bookings: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Booking';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['locationId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'location';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly city: { readonly column: 'city' };
                readonly region: { readonly column: 'region' };
                readonly country: { readonly column: 'country' };
                readonly status: { readonly column: 'status' };
                readonly phase: { readonly column: 'phase' };
                readonly type: { readonly column: 'type' };
                readonly address: { readonly column: 'address' };
                readonly landmark: { readonly column: 'landmark' };
                readonly phone: { readonly column: 'phone' };
                readonly bookingEnabled: { readonly column: 'bookingEnabled' };
                readonly clinicEnabled: { readonly column: 'clinicEnabled' };
                readonly atHomeEnabled: { readonly column: 'atHomeEnabled' };
                readonly nadxEnabled: { readonly column: 'nadxEnabled' };
              };
            };
          };
          readonly Membership: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly monthlyPrice: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly packagePrice: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly gst: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly totalPrice: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly active: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly bookings: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Booking';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['membershipId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'membership';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly type: { readonly column: 'type' };
                readonly monthlyPrice: { readonly column: 'monthlyPrice' };
                readonly packagePrice: { readonly column: 'packagePrice' };
                readonly gst: { readonly column: 'gst' };
                readonly totalPrice: { readonly column: 'totalPrice' };
                readonly description: { readonly column: 'description' };
                readonly active: { readonly column: 'active' };
              };
            };
          };
          readonly Protocol: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly number: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly family: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly shortDescription: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly duration: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly price: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly image: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly evidenceTier: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly active: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly bookings: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Booking';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['protocolId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'protocol';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly slug: { readonly column: 'slug' };
                readonly number: { readonly column: 'number' };
                readonly name: { readonly column: 'name' };
                readonly family: { readonly column: 'family' };
                readonly category: { readonly column: 'category' };
                readonly shortDescription: { readonly column: 'shortDescription' };
                readonly description: { readonly column: 'description' };
                readonly duration: { readonly column: 'duration' };
                readonly price: { readonly column: 'price' };
                readonly image: { readonly column: 'image' };
                readonly evidenceTier: { readonly column: 'evidenceTier' };
                readonly active: { readonly column: 'active' };
              };
            };
          };
        };
        readonly enum: {
          readonly BookingStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'CONFIRMED'; readonly value: 'CONFIRMED' },
              { readonly name: 'COMPLETED'; readonly value: 'COMPLETED' },
              { readonly name: 'CANCELLED'; readonly value: 'CANCELLED' },
              { readonly name: 'REJECTED'; readonly value: 'REJECTED' },
            ];
          };
          readonly LocationStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ACTIVE'; readonly value: 'ACTIVE' },
              { readonly name: 'EXPANSION'; readonly value: 'EXPANSION' },
            ];
          };
          readonly MembershipType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PACKAGE'; readonly value: 'PACKAGE' },
              { readonly name: 'UNLIMITED'; readonly value: 'UNLIMITED' },
              { readonly name: 'CIRCLE'; readonly value: 'CIRCLE' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'booking';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'customer';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'membership';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
